process.on('uncaughtException', e => { console.error(JSON.stringify({message:e.message,code:e.code,detail:e.detail})); process.exit(1); });
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const require = createRequire(resolve(process.argv[2], 'package.json'));
const {PGlite} = await import(pathToFileURL(require.resolve('@electric-sql/pglite')));
const {unaccent} = await import(pathToFileURL(require.resolve('@electric-sql/pglite/contrib/unaccent')));
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite({extensions:{unaccent}});
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE TABLE legal_documents(document_id bigint primary key,document_number text,title text,source_url text,legal_type text,issuing_authority text,issuance_date text,content text,content_sha256 text);
GRANT SELECT ON legal_documents TO anon,authenticated,service_role;`);
await db.exec(fs.readFileSync('migrations/20260919_legal_body_search.sql','utf8'));
const batch='11111111-1111-4111-8111-111111111111', hash='a'.repeat(64), body='Điều 24. Thử việc. Người lao động được thỏa thuận thời gian thử việc.';
await db.query('INSERT INTO legal_documents VALUES(1,$1,$2,$3,$4,$5,$6,$7,$8)',['test','Test fixture','','Luật','Test','2026-01-01',body,hash]);
await db.query('INSERT INTO legal_body_runs(batch_id,expected_documents,expected_passages,source_sha256) VALUES($1,1,1,$2)',[batch,hash]);
await db.query('INSERT INTO legal_body_passages(batch_id,document_id,section_id,section_title,document_offset,content_sha256,body) VALUES($1,1,$2,$3,0,$4,$5)',[batch,'section-1','Điều 24',hash,body]);
await db.exec('SET ROLE anon');
assert.equal((await db.query("SELECT * FROM search_legal_body('thu viec')")).rows.length,0);
await assert.rejects(db.query('SELECT publish_legal_body($1)',[batch]), /permission denied/);
await db.exec('RESET ROLE; SET ROLE service_role');
await db.query('SELECT publish_legal_body($1)',[batch]);
await db.exec('RESET ROLE; SET ROLE anon');
assert.equal((await db.query("SELECT * FROM search_legal_body('thu viec')")).rows.length,1);
assert.equal((await db.query("SELECT * FROM search_legal_body('thoi gian thu viec')")).rows.length,1);
assert.equal((await db.query("SELECT * FROM search_legal_body('thu nguoi viec')")).rows.length,0);
await assert.rejects(db.query("SELECT * FROM search_legal_body('thu viec',NULL)"), /invalid_body_query/);
await db.exec('RESET ROLE');
await db.query("UPDATE legal_documents SET content_sha256=$1",['b'.repeat(64)]);
await db.exec('SET ROLE anon');
assert.equal((await db.query("SELECT * FROM search_legal_body('thu viec')")).rows.length,0);
console.log(JSON.stringify({engine:'PGlite PostgreSQL',mock:false,fixture:'synthetic SQL contract fixture; not live corpus proof',passed:7}));
if (process.argv[3]) {
  await db.exec('RESET ROLE');
  const f=JSON.parse(fs.readFileSync(process.argv[3],'utf8'));
  const b='22222222-2222-4222-8222-222222222222';
  await db.query('INSERT INTO legal_documents VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[f.document_id,f.number,f.title,f.source_url,f.legal_type,f.authority,f.issuance_date,f.content,f.hash]);
  await db.query('INSERT INTO legal_body_runs(batch_id,expected_documents,expected_passages,source_sha256) VALUES($1,1,1,$2)',[b,f.hash]);
  await db.query('INSERT INTO legal_body_passages VALUES($1,$2,$3,$4,$5,$6,$7,DEFAULT)',[b,f.document_id,f.section_id,'Điều 24',f.offset,f.hash,f.body]);
  await db.exec('SET ROLE service_role');
  await db.query('SELECT publish_legal_body($1)',[b]);
  await db.exec('RESET ROLE; SET ROLE anon');
  const hits=(await db.query("SELECT * FROM search_legal_body('thu viec')")).rows;
  assert.equal(hits.length,1); assert.equal(hits[0].document_id,f.document_id); assert.equal(hits[0].section_id,f.section_id);
  console.log(JSON.stringify({fixture:'real local corpus',document_id:f.document_id,number:f.number,hash:f.hash,hits:hits.length,anchor:hits[0].section_id}));
}
await db.close();
