import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(resolve(process.argv[2],'package.json'));
const {PGlite}=await import(pathToFileURL(require.resolve('@electric-sql/pglite')));
const {unaccent}=await import(pathToFileURL(require.resolve('@electric-sql/pglite/contrib/unaccent')));
process.on('uncaughtException',e=>{console.error(JSON.stringify({error:e.message,code:e.code}));process.exit(1);});
const folder=process.argv[3], m=JSON.parse(fs.readFileSync(resolve(folder,'manifest.json'),'utf8'));
const docs=JSON.parse(fs.readFileSync(resolve(folder,'source-documents.json'),'utf8'));
const rows=fs.readFileSync(resolve(folder,'passages.jsonl'),'utf8').trim().split('\n').map(JSON.parse);
const db=new PGlite({extensions:{unaccent}});
await db.exec('CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE TABLE legal_documents(document_id bigint primary key,document_number text,title text,source_url text,legal_type text,issuing_authority text,issuance_date text,content text,content_sha256 text); GRANT SELECT ON legal_documents TO anon,authenticated,service_role;');
await db.exec(fs.readFileSync('migrations/20260919_legal_body_search.sql','utf8'));
for(const d of docs) {const x=d.metadata;await db.query('INSERT INTO legal_documents VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[x.document_id,x.document_number,x.title,x.source_url,x.legal_type,x.issuing_authority,x.issuance_date,d.content,d.content_sha256]);}
await db.query('INSERT INTO legal_body_runs(batch_id,expected_documents,expected_passages,source_sha256) VALUES($1,$2,$3,$4)',[m.batch_id,m.expected_documents,m.expected_passages,m.source_sha256]);
for(const r of rows) await db.query('INSERT INTO legal_body_passages VALUES($1,$2,$3,$4,$5,$6,$7,DEFAULT)',[r.batch_id,r.document_id,r.section_id,r.section_title,r.document_offset,r.content_sha256,r.body]);
const first=rows[0], query=first.body.trim().split(/\s+/).slice(0,5).join(' ');
await db.exec('SET ROLE anon');
assert.equal((await db.query('SELECT * FROM search_legal_body($1)',[query])).rows.length,0);
await db.exec('RESET ROLE');
await db.query('UPDATE legal_body_passages SET document_offset=document_offset+1 WHERE batch_id=$1 AND document_id=$2 AND document_offset=$3',[m.batch_id,first.document_id,first.document_offset]);
await db.exec('SET ROLE service_role');
await assert.rejects(db.query('SELECT publish_legal_body($1)',[m.batch_id]),/body_source_mismatch/);
assert.equal((await db.query('SELECT legal_body_coverage() AS coverage')).rows[0].coverage,null);
await db.exec('RESET ROLE');
await db.query('UPDATE legal_body_passages SET document_offset=$3 WHERE batch_id=$1 AND document_id=$2 AND document_offset=$4',[m.batch_id,first.document_id,first.document_offset,first.document_offset+1]);
await db.exec('SET ROLE service_role');
await db.query('SELECT publish_legal_body($1)',[m.batch_id]);
await db.exec('RESET ROLE; SET ROLE anon');
const coverage=(await db.query('SELECT legal_body_coverage() AS coverage')).rows[0].coverage;
assert.equal(coverage.document_count,docs.length);assert.equal(coverage.passage_count,rows.length);
const hits=(await db.query('SELECT * FROM search_legal_body($1,51)',[query])).rows;
assert.ok(hits.some(h=>h.document_id==first.document_id));
assert.equal((await db.query("SELECT * FROM search_legal_body($1,51,0,'nonexistent-type')",[query])).rows.length,0);
console.log(JSON.stringify({engine:'PGlite PostgreSQL',source:'real ContentStore documents',documents:docs.length,passages:rows.length,query,hits:hits.length,source_sha256:m.source_sha256,invalid_offset_rejected:true,unpublished_batch_hidden:true,filter_verified:true}));
await db.close();
