import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import fs from 'node:fs';
import assert from 'node:assert/strict';

const require = createRequire(resolve(process.argv[2], 'package.json'));
const {PGlite} = await import(pathToFileURL(require.resolve('@electric-sql/pglite')));
const {unaccent} = await import(pathToFileURL(require.resolve('@electric-sql/pglite/contrib/unaccent')));
const db = new PGlite({extensions:{unaccent}});
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE SCHEMA extensions; CREATE EXTENSION unaccent WITH SCHEMA extensions;
CREATE TEXT SEARCH CONFIGURATION public.vietlex_body_simple (COPY = pg_catalog.simple);
ALTER TEXT SEARCH CONFIGURATION public.vietlex_body_simple ALTER MAPPING FOR hword, hword_part, word WITH extensions.unaccent, pg_catalog.simple;
CREATE TABLE public.legal_documents(document_id bigint primary key,document_number text,title text,source_url text,legal_type text,issuing_authority text,issuance_date text,content text,content_sha256 text);
ALTER TABLE public.legal_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY documents_read ON public.legal_documents FOR SELECT TO anon,authenticated USING (true);
GRANT SELECT ON public.legal_documents TO anon,authenticated,service_role;`);
const migration = fs.readFileSync('migrations/20260925_legal_full_doc_search.sql','utf8');
const functionStart = migration.indexOf('CREATE OR REPLACE FUNCTION');
await db.exec(migration.slice(0,functionStart));
await db.exec(migration.slice(functionStart));
await db.query('INSERT INTO legal_documents VALUES(1,$1,$2,$3,$4,$5,$6,$7,$8)', ['45/2019/QH14','Test','','Bộ luật','Quốc hội','2019-11-20','Điều 25. Thời gian thử việc không quá 60 ngày.','a'.repeat(64)]);
await db.query('INSERT INTO legal_documents VALUES(2,$1,$2,$3,$4,$5,$6,$7,$8)', ['02/2020','Other','','Nghị định','Chính phủ','2020-01-01','Điều 1. Thử người việc không đúng cụm.','b'.repeat(64)]);
await db.query('INSERT INTO legal_documents VALUES(3,$1,$2,$3,$4,$5,$6,$7,$8)', ['03/2020','Long','','Luật','Quốc hội','2020-01-02','Điều 1. '+ 'chung '.repeat(20000) + 'nhiệm vụ đặc biệt cuối văn bản.','c'.repeat(64)]);
await db.exec('SET ROLE anon');
await db.exec('SET enable_seqscan=off');
const plan = (await db.query("EXPLAIN SELECT document_id FROM legal_documents WHERE document_id % 8 = 1 AND to_tsvector('public.vietlex_body_simple'::regconfig,content) @@ plainto_tsquery('public.vietlex_body_simple'::regconfig,'thu viec')")).rows.map(row=>row['QUERY PLAN']).join('\n');
assert.match(plan,/legal_documents_body_fts_v1_1/);
await db.exec('RESET enable_seqscan');
const coverage = (await db.query('SELECT legal_full_doc_coverage() AS coverage')).rows[0].coverage;
assert.equal(coverage.index_version,1);
assert.equal(coverage.document_count,3);
const hit = (await db.query("SELECT * FROM search_legal_full_doc('thoi gian thu viec')")).rows;
assert.equal(hit.length,1);
assert.equal(Number(hit[0].document_id),1);
assert.equal((await db.query("SELECT * FROM search_legal_full_doc('thu nguoi viec')")).rows.length,1);
assert.equal((await db.query("SELECT * FROM search_legal_full_doc('viec gian thoi')")).rows.length,0);
assert.equal((await db.query("SELECT * FROM search_legal_full_doc('thu viec',20,0,'Nghị định')")).rows.length,0);
assert.equal((await db.query("SELECT * FROM search_legal_full_doc('thu viec',20,1)")).rows.length,0);
assert.equal((await db.query("SELECT * FROM search_legal_full_doc('nhiem vu dac biet cuoi van ban')")).rows.length,1);
await assert.rejects(db.query("SELECT * FROM search_legal_full_doc('thu viec',NULL)"),/invalid_body_query/);
console.log(JSON.stringify({engine:'PGlite PostgreSQL',passed:10}));
await db.close();
